### ISSUE TITLE
root application recursive ?

### ISSUE THREAD

**Issue by mzamoun** [hotblac/voicexmlriot#2]
can we have this structure : 
file1.vxml have a root application : file2.vxml 
file2.vxml have a root application : file3.vxml 

if not, how to importe file3 in file2  ?

**Comment by hotblac** [comment]
Not sure what you mean there. Do you have an example you can post in GitHub?

If you just want to import an XML file into another, does this help? https://stackoverflow.com/questions/5121052/can-we-import-xml-file-into-another-xml-file

**Comment by mzamoun** [comment]
I tried it but not work !! 
I have this error : 
Caused by: org.xml.sax.SAXException: Scanner State 24 not Recognized 
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)

**Comment by hotblac** [comment]
Does this work in JVoiceXML? VoiceXMLRiot is a test framework for VoiceXML applications using the JVoiceXML browser. If this doesn't work in JVoiceXML then VoiceXMLRiot behaves as expected.

**Comment by hotblac** [comment]
Closing: no update in last month
