### ISSUE TITLE
audio expr is not detected !!

### ISSUE THREAD

**Issue by mzamoun** [hotblac/voicexmlriot#3]
the code : 
        < prompt bargein="false" >
			< audio src="file_to_play.wav" / >
		< / prompt >
is good detected.

But this one, NO !? : 
        < prompt bargein="false" >
			< audio expr="file_to_play"  / >
		< / prompt > 

Is there an explaination  please ?

**Comment by hotblac** [comment]
I've added a test case successfully demonstrating audio src evaluated by ECMAScript expression:
https://github.com/hotblac/voicexmlriot/commit/58a134a356670e5fd37ae0c70a59c209aa35ea13

Can you please try that and let me know if this works?

**Comment by mzamoun** [comment]
I see that you have change your project. How to update my projects cloned from yours ?

**Comment by mzamoun** [comment]
your example works
but mine who use a function in the root application dosen't work !!?

**Comment by hotblac** [comment]
Does this work in JVoiceXML? VoiceXMLRiot is a test framework for VoiceXML applications using the JVoiceXML browser. If this doesn't work in JVoiceXML then VoiceXMLRiot behaves as expected.

**Comment by hotblac** [comment]
Closing: no update in last month
