### ISSUE TITLE
why we cant do a tag script before a tag form ?

### ISSUE THREAD

**Issue by mzamoun** [hotblac/voicexmlriot#5]
for example : this code dose  not work !! ??
< script > var x = 0; < / script >
< form > 
   ...
< / form >

**Comment by hotblac** [comment]
Does this work in JVoiceXML? VoiceXMLRiot is a test framework for VoiceXML applications using the JVoiceXML browser. If this doesn't work in JVoiceXML then VoiceXMLRiot behaves as expected.

**Comment by hotblac** [comment]
Closing: no update in last month
