### ISSUE TITLE
audio expr : not work simply !

### ISSUE THREAD

**Issue by mzamoun** [hotblac/voicexmlriot#6]
if i use : 
< audio expr="my_var + ''" / > it works .
but if i use : 
< audio expr="my_var" / > it DOSENT works  !!??

**Comment by hotblac** [comment]
Does this work in JVoiceXML? VoiceXMLRiot is a test framework for VoiceXML applications using the JVoiceXML browser. If this doesn't work in JVoiceXML then VoiceXMLRiot behaves as expected.

**Comment by hotblac** [comment]
Closing: no update in last month
